### ISSUE TITLE
"Smart Demodulator Block"

### ISSUE THREAD

**Issue by mbr0wn** [sbmueller/gsoc-proposal#1]
I'm not sure what that's supposed to be. Also, it would be much more useful if you could use a "dumb demodulator block". You want to reimplement as little as possible, right?

**Comment by sbmueller** [comment]
Yes, "smart" with the meaning of choosing the correct demodulator with no necessary user input. So this block would work as kind of a demux component (as planned for now). As I should focus on fewer aspects of the signal intelligence workflow (#4), I will maybe reduce the "additional deliverables" to an outlook for the post-GSoC period.
