### ISSUE TITLE
Underestimation of effort

### ISSUE THREAD

**Issue by mbr0wn** [sbmueller/gsoc-proposal#2]
I think you're severely underestimating the difficulty of this.

**Comment by sbmueller** [comment]
Right, this is actually a lot of work. I tried to point out that I will first focus on the core deliverables (signal detection + modulation classification + GUI + documentation). If I managed to finish these tasks before pencils down, I would begin with the additional deliverables (demod, etc.). The current timeline would be the ideal case where I am able to finish all tasks. As pointed out in #4 I will try to reduce the deliverables to the most important ones and change my timeline accordingly.
